[toolchain]
rust = { version = "1.70.0" }

[features]
skip-lint = false

[programs.localnet]
sol_collector = "11111111111111111111111111111111"

[programs.devnet]
sol_collector = "11111111111111111111111111111111"

[programs.mainnet]
sol_collector = "11111111111111111111111111111111"

[registry]
url = "https://api.github.com/repos/project-serum/anchor/releases/download/v0.29.0/anchor-platform-linux-gnu-0.29.0.tar.gz"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha --timeout 1000000 tests/**/*.ts"
